### ISSUE TITLE
ValueError: date encoding field is specified without a type

### ISSUE THREAD

**Issue by robmarkcole** [bendoesdata/panel-altair-dashboard#2]
Hi
I hit this error:
```
019-08-24 16:29:38,372 Error running application handler <bokeh.application.handlers.notebook.NotebookHandler object at 0x11e58ceb8>: date encoding field is specified without a type; the type cannot be automatically inferred because the data is not specified as a pandas.DataFrame.
File "channels.py", line 48, in to_dict:
"".format(self.shorthand)) Traceback (most recent call last):
  File "//anaconda3/lib/python3.7/site-packages/bokeh/application/handlers/code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "/Users/robin/Github/panel-altair-dashboard/panel-altair-demo.ipynb", line 85, in <module>
    "      const element = document.createElement(\"link\");\n",
  File "//anaconda3/lib/python3.7/site-packages/panel/viewable.py", line 480, in servable
    self.server_doc(title=title)
  File "//anaconda3/lib/python3.7/site-packages/panel/viewable.py", line 457, in server_doc
    model = self.get_root(doc)
  File "//anaconda3/lib/python3.7/site-packages/panel/viewable.py", line 400, in get_root
    root = self._get_model(doc, comm=comm)
  File "//anaconda3/lib/python3.7/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "//anaconda3/lib/python3.7/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "//anaconda3/lib/python3.7/site-packages/panel/param.py", line 607, in _get_model
    model = self._inner_layout._get_model(doc, root, parent, comm)
  File "//anaconda3/lib/python3.7/site-packages/panel/layout.py", line 105, in _get_model
    objects = self._get_objects(model, [], doc, root, comm)
  File "//anaconda3/lib/python3.7/site-packages/panel/layout.py", line 94, in _get_objects
    child = pane._get_model(doc, root, model, comm)
  File "//anaconda3/lib/python3.7/site-packages/panel/pane/vega.py", line 105, in _get_model
    json = self._to_json(self.object)
  File "//anaconda3/lib/python3.7/site-packages/panel/pane/vega.py", line 66, in _to_json
    return obj.to_dict()
  File "//anaconda3/lib/python3.7/site-packages/altair/vegalite/v3/api.py", line 369, in to_dict
    dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)
  File "//anaconda3/lib/python3.7/site-packages/altair/utils/schemapi.py", line 285, in to_dict
    validate=sub_validate, context=context)
  File "//anaconda3/lib/python3.7/site-packages/altair/utils/schemapi.py", line 50, in _todict
    return {k: _todict(v, validate, context) for k, v in obj.items()
  File "//anaconda3/lib/python3.7/site-packages/altair/utils/schemapi.py", line 51, in <dictcomp>
    if v is not Undefined}
  File "//anaconda3/lib/python3.7/site-packages/altair/utils/schemapi.py", line 46, in _todict
    return obj.to_dict(validate=validate, context=context)
  File "//anaconda3/lib/python3.7/site-packages/altair/utils/schemapi.py", line 285, in to_dict
    validate=sub_validate, context=context)
  File "//anaconda3/lib/python3.7/site-packages/altair/utils/schemapi.py", line 50, in _todict
    return {k: _todict(v, validate, context) for k, v in obj.items()
  File "//anaconda3/lib/python3.7/site-packages/altair/utils/schemapi.py", line 51, in <dictcomp>
    if v is not Undefined}
  File "//anaconda3/lib/python3.7/site-packages/altair/utils/schemapi.py", line 46, in _todict
    return obj.to_dict(validate=validate, context=context)
  File "//anaconda3/lib/python3.7/site-packages/altair/vegalite/v3/schema/channels.py", line 28, in to_dict
    for shorthand in self.shorthand]
  File "//anaconda3/lib/python3.7/site-packages/altair/vegalite/v3/schema/channels.py", line 28, in <listcomp>
    for shorthand in self.shorthand]
  File "//anaconda3/lib/python3.7/site-packages/altair/vegalite/v3/schema/channels.py", line 48, in to_dict
    "".format(self.shorthand))
ValueError: date encoding field is specified without a type; the type cannot be automatically inferred because the data is not specified as a pandas.DataFrame.
 ``

Pandas 0.24.2
Altair 3.1.0
Panel 0.6.0

**Comment by bendoesdata** [comment]
Hey Rob,

So this looks like a data formatting issue. Are you passing your data as a Pandas Dataframe before loading it into the Altair chart object? (re: error message `data is not specified as a pandas.DataFrame.`)

Alternatively, it could be on Altair's side. This message:

`date encoding field is specified without a type`

means you need to tell Altair what type of data you are passing in each column. The "date" column will be type `T` and you would specify it like this: `"date:T"`. The other type of data would be for quantitative, which is `Q`. You can read more about specifying data types in the [Altair docs](https://altair-viz.github.io/user_guide/data.html).

That being said, if you format your Pandas dataframe "date" column as `datetime` before passing it to Altair, you shouldn't have to specify the type explicitly.

Let me know if that helps.

**Comment by fonnesbeck** [comment]
I'm getting the same issue, and this is running the notebook as-is, using the data in the example.

**Comment by fonnesbeck** [comment]
FWIW, passing types to Altair does not fix the issue, i.e.: `encode(x='date:T', y='price:Q' ...`

**Comment by robmarkcole** [comment]
Hi @bendoesdata 
I am also using the default data source from your notebook. The error arises at:
```
alt.Chart(df).mark_area(color="#0c1944", opacity=0.8).encode(x='date', y='price', tooltip=alt.Tooltip(['date','price'])).transform_filter(
        (datum.symbol == ticker) # this ties in the filter from the dropdown selection
)

...
ValueError: date encoding field is specified without a type; the type cannot be automatically inferred because the data is not specified as a pandas.DataFrame.
```

**Comment by robmarkcole** [comment]
OK so I updated altair from 3.1 to 3.2 and this issue is resolved. I recommend including a conda environment.yaml file in this repo. Thanks

**Comment by bendoesdata** [comment]
Hey Rob, that's great the issue resolved. My next suggestion was going to be investigating package versions. I installed everything fresh using conda, so perhaps I''ll update the tutorial to include that note.

@fonnesbeck I recommend updating your packages, starting first with Altair to see if that resolves it.
